name=input('name:')
surname=input('surname:')
age=input('age:')
num1=input('num1:')
num2=('num2:')
print(name)
print(surname)
print(age)
print(num1)
print(num2)

print(type(name))
print(type(surname))
print(type(age))
print(type(num1))
print(type(num2))
