num = int(input("1. enter your number: "))
num1 = int(input("1. enter your number: "))
num2 = int(input("1. enter your number: "))
num3 = int(input("1. enter your number: "))
num4 = int(input("1. enter your number: "))
num5 = int(input("1. enter your number: "))
num6 = int(input("1. enter your number: "))
num7 = int(input("1. enter your number: "))
num8 = int(input("1. enter your number: "))
num9 = int(input("1. enter your number: "))
print(num + num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9)